<?php

namespace Dscorp\Cart\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\DBAL\DriverManager;

/**
 * ProductoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductoRepositorio extends EntityRepository
{

/*public function findBlogs() {
        $em = $this->getEntityManager();
        $dql = "select b,s
            from AdminProdBundle:blog b
            join b.imagenes s
             ";//group by p.id

        $query = $em->createQuery($dql);
        //$query->setParameter('id', $id);
        $producto = $query->getArrayResult();
       // echo '<pre>';print_r($producto);echo '</pre>';
        return $producto;
     }
    public function findBlogsByid($id) {
        $em = $this->getEntityManager();
        $dql = "select b,s
            from AdminProdBundle:blog b
            join b.imagenes s
            where b.id= :id ";//group by p.id

        $query = $em->createQuery($dql);
        $query->setParameter('id', $id);
        $producto = $query->getArrayResult();
       // echo '<pre>';print_r($producto);echo '</pre>';
        return $producto[0];
     }
    public function findBlogsBycat($id) {
        $em = $this->getEntityManager();
        $dql = "select b,s
            from AdminProdBundle:blog b
            join b.imagenes s
            where b.categoria=:id ";//group by p.id

        $query = $em->createQuery($dql);
        $query->setParameter('id', $id);
        $producto = $query->getArrayResult();
       // echo '<pre>';print_r($producto);echo '</pre>';
        return $producto;
     }*/
     
	public function findProducto($id) {
	    $em = $this->getEntityManager();
        $dql = "select s,a
            from AdminBundle:AdminProd a
            join a.imagen s
            where m.id=:id ";//group by p.id

        $query = $em->createQuery($dql);
        $query->setParameter('id', $id);
        $producto = $query->getArrayResult();
       // echo '<pre>';print_r($producto);echo '</pre>';
        return $producto;
     }
     public function findProductoLike($id) {
        $em = $this->getEntityManager();
        $dql = "select s,a
            from AdminBundle:AdminProd a
            join a.imagen s
            where a.nombre like :id ";//group by p.id

        $query = $em->createQuery($dql);
        $query->setParameter('id', '%'.$id.'%');
        $producto = $query->getArrayResult();
       // echo '<pre>';print_r($producto);echo '</pre>';
        return $producto;
     }

     public function findAllProducto() {
        $em = $this->getEntityManager();
        $dql = "select s,a
            from AdminBundle:AdminProd a
            join a.imagen s;
            where m.id=:id ";//group by p.id

        $query = $em->createQuery($dql);
       // $query->setParameter('id', $id);
        $producto = $query->getArrayResult();
       // echo '<pre>';print_r($producto);echo '</pre>';
        return $producto;
     }

    public function findAllBycart($id) {
        $em = $this->getEntityManager();
        $dql = "select a,i
            from AdminBundle:AdminProd a
            join a.itemCart i
            where i.cart=:id ";//group by p.id

        $query = $em->createQuery($dql);
       $query->setParameter('id', $id);
        $producto = $query->getArrayResult();
       // echo '<pre>';print_r($producto);echo '</pre>';
        return $producto;
     }

      public function findAllByitem($id) {
        $em = $this->getEntityManager();
        $dql = "select a,i
            from AdminBundle:AdminProd a
            join a.itemCart i
            where i.id=:id ";//group by p.id

        $query = $em->createQuery($dql);
       $query->setParameter('id', $id);
        $producto = $query->getArrayResult();
       // echo '<pre>';print_r($producto);echo '</pre>';
        return $producto[0];
     }

     public function findOfertas() {
        $em = $this->getEntityManager();
        $dql = "select s,a
            from AdminBundle:AdminProd a
            join a.imagen s
            ";//group by p.id

        $query = $em->createQuery($dql);
       //$query->setParameter('id', $id);
        $producto = $query->getArrayResult();
       // echo '<pre>';print_r($producto);echo '</pre>';
        return $producto;
     }
}
